### ISSUE TITLE
Get row count

### ISSUE THREAD

**Issue by lucielavickova** [peterservice-rnd/robotframework-excellibrary#1]
Hello! 
First, I would like to thank you for creating this library, it's great to have finally a library that works with XLSX files :) 
I am only missing one keyword - **get row count** that would enable me to loop through the rows in an excel sheet. Would it be possible to implement it? 
Thank you :)

**Comment by dmizverev** [comment]
@aleskarovadi , I think that [_get_sheet](https://github.com/peterservice-rnd/robotframework-excellib/blob/master/src/ExcelLibrary.py#L183) should not be private.
Like this:
```robotframework
Open Excel Document    filename=file.xlsx    doc_id=docid 
${sheet1}=   Get sheet    Sheet1 
Comment    Print first row 
Log    ${sheet1.rows}[1] 
```

**Comment by aleskarovadi** [comment]
@lucietriskova, hello!

Method `get_sheet` is public now, so you can loop through the rows:
```robot
Open Excel Document    filename=file.xlsx    doc_id=docid 
${sheet1}=    Get sheet    Sheet1 
:FOR     ${row}    IN    @{sheet1.values}
\    Log     ${row}
```

See more information in [openpyxl.worksheet documentation](https://openpyxl.readthedocs.io/en/stable/api/openpyxl.worksheet.worksheet.html).

These changes are now availble on [PyPi](https://pypi.org/project/robotframework-excellib/1.1.0/) (version 1.1.0 of robotframework-excellib)
