### ISSUE TITLE
Install Command line does not the same last commit

### ISSUE THREAD

**Issue by ghost** [peterservice-rnd/robotframework-excellibrary#8]
I Installed Command line

> pip install robotframework-excellib

So, Version control is 1.1.0 but I found last commit version 2.0.0 is not not the same.

Could you please update ? Thank you.

**Comment by ailjushkin** [comment]
@Lev-v please update release version in pypi.
@lachesschoc you can temporarily install the package from the master branch directly.

`pip install https://github.com/peterservice-rnd/robotframework-excellib/archive/master.zip`

**Comment by Lev-v** [comment]
@ailjushkin @lachesschoc Thank you, I fixed the issue, last version can now be installed using default pip command as it should be.

**Comment by ailjushkin** [comment]
That's awesome, man. Thank you
